name: foodFinalProj
channels:
  - defaults
dependencies:
  - matplotlib=3.6.0
  - numpy=1.23.3
  - python=3.9
  - scipy
  - pillow
  - pandas
  - jupyter
  - opencv
  - scikit-learn
  - tensorflow
  - pip
  - pip:
      - jupyterlab
